/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	darkMode: 'class',
	theme: {
		extend: {
			colors: {
				surface: '#19120a',
				'surface-dim': '#19120a',
				'surface-bright': '#40382e',
				'surface-container-lowest': '#130d06',
				'surface-container-low': '#211a12',
				'surface-container': '#251e16',
				'surface-container-high': '#302920',
				'surface-container-highest': '#3c332a',
				'on-surface': '#eee0d2',
				'on-surface-variant': '#d7c3ae',
				'inverse-surface': '#eee0d2',
				'inverse-on-surface': '#372f26',
				outline: '#9f8e7a',
				'outline-variant': '#524534',
				'surface-tint': '#ffb955',
				primary: '#ffc880',
				'on-primary': '#452b00',
				'primary-container': '#f5a623',
				'on-primary-container': '#644000',
				'inverse-primary': '#835500',
				secondary: '#c5c1f5',
				'on-secondary': '#2d2b55',
				'secondary-container': '#464470',
				'on-secondary-container': '#b7b3e6',
				tertiary: '#9bd9ff',
				'on-tertiary': '#00344a',
				'tertiary-container': '#3ac2ff',
				'on-tertiary-container': '#004d6a',
				error: '#ffb4ab',
				'on-error': '#690005',
				'error-container': '#93000a',
				'on-error-container': '#ffdad6',
				'primary-fixed': '#ffddb4',
				'primary-fixed-dim': '#ffb955',
				'on-primary-fixed': '#291800',
				'on-primary-fixed-variant': '#633f00',
				'secondary-fixed': '#e3dfff',
				'secondary-fixed-dim': '#c5c1f5',
				'on-secondary-fixed': '#18163f',
				'on-secondary-fixed-variant': '#44426d',
				'tertiary-fixed': '#c4e7ff',
				'tertiary-fixed-dim': '#7cd0ff',
				'on-tertiary-fixed': '#001e2c',
				'on-tertiary-fixed-variant': '#004c69',
				background: '#19120a',
				'on-background': '#eee0d2',
				'surface-variant': '#3c332a',
			},
			borderRadius: {
				DEFAULT: '0.5rem',
				lg: '1rem',
				xl: '1.5rem',
			},
			spacing: {
				'section-gap': '120px',
				'margin-desktop': '64px',
				unit: '8px',
				'margin-mobile': '20px',
				gutter: '24px',
				'container-max': '1200px',
			},
			fontFamily: {
				display: ['"Hanken Grotesk"', 'system-ui', 'sans-serif'],
				body: ['Inter', 'system-ui', 'sans-serif'],
				mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
			},
			fontSize: {
				'label-mono': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
				'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
				'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
				'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
				'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
				'display-lg-mobile': ['40px', { lineHeight: '1.2', fontWeight: '800' }],
				button: ['16px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '600' }],
			},
			maxWidth: {
				'container-max': '1200px',
			},
		},
	},
	plugins: [],
};
